"""
MILKY WAY <-> ANDROMEDA: an interactive galaxy-collision laboratory
=====================================================================

Run with:  uv run --python 3.12 --with taichi sim.py

PHYSICAL MODEL (read this before touching constants)
------------------------------------------------------------------------
Simulating tens of thousands of stars with true pairwise (star-to-star)
gravity is O(N^2) and is exactly the "computationally unrealistic
brute-force" approach we were told to avoid -- on integrated laptop
graphics it would crawl at a few frames per *minute*, not per second.

Instead we use the classic technique that was actually used to *discover*
tidal tails and bridges (Toomre & Toomre, 1972, "Galactic Bridges and
Tails"), extended with a small multipole expansion instead of a single
point mass per galaxy:

    * Each galaxy's gravity field is generated by a small "macro-particle
      skeleton": one dense central mass (bulge/core) plus a handful of
      ring masses that trace the disk's mass profile. There are only
      N_MACRO (~50) of these, so they can be evolved with an *exact*
      pairwise N-body sum (50^2 = 2500 pair checks -- trivial).
    * Thousands of individual stars are massless "test particles" that
      feel gravity FROM the macro-skeleton (an O(N_stars * N_macro) sum,
      fully data-parallel, and cheap: ~50 force evaluations per star)
      but do not pull on each other or on the skeleton. This is exactly
      how real restricted N-body galaxy-merger movies are made, and it
      is why stars never "collide": they only ever respond to the smooth
      large-scale field, never to one another.

This is a reduced-order approximation of full self-gravitating N-body
dynamics (real disks are also stabilized/perturbed by their own
star-star self-gravity, which we do not model star-by-star). It still
reproduces the real, famous phenomena: differential rotation winding up
a seeded spiral pattern, tidal stretching of the encounter into long
stellar streams, a close flyby, a fall-back, and -- thanks to a small
dynamical-friction drag standing in for the drag of the extended dark
matter halos (Chandrasekhar 1943) -- an eventual merger into one remnant.

UNITS
------------------------------------------------------------------------
Galaxy-scale dynamics does not fit comfortably into AU / solar mass /
year (numbers become >10^9), so -- keeping the *spirit* of "pick units
where G is a simple constant and numbers stay near order-1" -- we use
standard galactic N-body units instead:

    length unit   L0 = 1 kpc
    mass unit     M0 = 1e11 solar masses
    G_SIM         = 1.0   (by construction of the unit system below)

Given the real gravitational constant G_real = 4.30091e-6 kpc*(km/s)^2 /
Msun, setting G_SIM = 1 fixes the remaining units:
    velocity unit V0 = sqrt(G_real * M0 / L0) = 655.8 km/s
    time unit     T0 = L0 / V0               = 1.49 Myr
So "10 time units" of simulation is about 15 Myr of real time, and a
star drifting at "1" is moving at ~656 km/s. All constants below are
named and commented in these units so a physics student can check them.

CONTROLS (also printed to the console at startup)
------------------------------------------------------------------------
  Left-drag         orbit the camera around the system
  Right-drag        pan the camera target
  W , S             zoom in / out (dolly)
  SPACE             pause / resume
  R                 reset the simulation
  ] / [ (or UP/DOWN)  speed up / slow down simulation time
  Shift + Left-click  fire a burst of probe stars into the field at the
                      cursor (projected onto the galactic mid-plane)
  G                 toggle the reference grid
  T                 toggle orbit trails
  ESC               quit
"""

import os
import numpy as np
import taichi as ti

try:
    ti.init(arch=ti.gpu)
except Exception:
    ti.init(arch=ti.cpu)
    print("Running on CPU, expect lower FPS. Lower the body count if it crawls.")

# =========================================================================
# 0. UNITS AND GLOBAL PHYSICAL CONSTANTS
# =========================================================================
G_SIM = 1.0          # gravitational constant in our N-body unit system (see header)
KPC_PER_UNIT = 1.0   # length unit  L0 = 1 kpc
MSUN_PER_UNIT = 1.0e11  # mass unit   M0 = 1e11 solar masses
MYR_PER_TIME_UNIT = 1.49  # time unit  T0 ~= 1.49 Myr (derived from G_real, see header)
KMS_PER_VEL_UNIT = 655.8   # velocity unit V0 ~= 656 km/s

# Softening length: real stars have zero radius, but our "stars" are tracer
# particles standing in for huge (~10^6-10^8 solar mass) clumps of real
# stars, and our "macro masses" stand in for whole mass concentrations.
# Without softening, a close pass between two point masses gives an
# unphysical infinite-force slingshot. SOFTENING sets the distance below
# which gravity is smoothly capped, mimicking the finite size of a real
# bulge/disk mass concentration.
SOFTENING = 0.18          # kpc-equivalent softening length
SOFTENING2 = SOFTENING * SOFTENING

# =========================================================================
# 1. GALAXY STRUCTURE PARAMETERS
# =========================================================================
RINGS_PER_GALAXY = 3
MACROS_PER_RING = 8
N_MACRO_PER_GALAXY = 1 + RINGS_PER_GALAXY * MACROS_PER_RING   # 1 core + rings
N_MACRO = 2 * N_MACRO_PER_GALAXY                              # both galaxies

# Fraction of a galaxy's total mass carried by the core vs. each ring,
# loosely modeling a bulge + declining exponential disk mass profile.
CORE_MASS_FRAC = 0.35
RING_MASS_FRAC = np.array([0.30, 0.22, 0.13])   # inner -> outer ring
RING_RADIUS_FRAC = np.array([0.30, 0.55, 0.90])  # as a fraction of disk radius

# Number of individually-rendered tracer stars per galaxy. This is the
# main visual-density vs. performance knob -- raise it if your GPU keeps
# up smoothly, lower it if the frame rate sags below ~30 fps.
N_STARS_PER_GALAXY = 14000
N_USER_POOL = 3000              # reserved slots for user-spawned probe stars
N_STARS = 2 * N_STARS_PER_GALAXY + N_USER_POOL

BULGE_FRACTION = 0.16   # fraction of each galaxy's stars placed in a puffy central bulge

# --- Milky Way analogue ("galaxy 0") ---
MASS_A = 10.0        # 1e12 Msun total (incl. dark-matter-proxy mass in the rings)
DISK_RADIUS_A = 9.0  # kpc, extent of the visible star-forming disk
DISK_THICKNESS_A = 0.35

# --- Andromeda analogue ("galaxy 1"), slightly more massive & larger, as in reality ---
MASS_B = 14.0
DISK_RADIUS_B = 10.5
DISK_THICKNESS_B = 0.40

# Orbital encounter geometry (Toomre & Toomre style prograde-ish flyby):
INITIAL_SEPARATION = 58.0     # kpc between galaxy centers at t=0
IMPACT_PARAMETER = 13.0       # kpc perpendicular offset -> non-head-on grazing pass
INFALL_SPEED = 0.16           # closing speed, in velocity units (~105 km/s)

# Simplified Chandrasekhar dynamical-friction coefficient: represents
# momentum drained from the galaxies' relative orbit into their extended
# (unmodeled) dark-matter halos as they pass through one another. This is
# what allows a flyby to fall back and finally coalesce into one remnant
# within a watchable simulated time, instead of orbiting forever.
DYN_FRICTION_COEFF = 0.85
DYN_FRICTION_CORE_RADIUS = 14.0   # kpc, sets how "spread out" the halo drag is
VELOCITY_SOFTENING = 0.03         # avoids a division singularity as v_rel -> 0

# Distance from the system barycenter beyond which a star is considered
# "lost" and is recycled back into the live structure (keeps the show
# alive forever without ever-expanding, ever-thinning debris).
ESCAPE_RADIUS = 340.0

# =========================================================================
# 2. TIME INTEGRATION PARAMETERS
# =========================================================================
DT_BASE = 0.02              # base leapfrog timestep, in time units (~30,000 yr)
STEPS_PER_FRAME_BASE = 4    # physics substeps per rendered frame at 1x speed
MIN_TIME_SCALE = 0.15
MAX_TIME_SCALE = 10.0
MAX_STEPS_PER_FRAME = 48    # safety clamp so a huge time_scale can't stall the UI

# =========================================================================
# 3. TAICHI FIELDS
# =========================================================================
macro_pos = ti.Vector.field(3, ti.f32, shape=N_MACRO)
macro_vel = ti.Vector.field(3, ti.f32, shape=N_MACRO)
macro_acc = ti.Vector.field(3, ti.f32, shape=N_MACRO)
macro_mass = ti.field(ti.f32, shape=N_MACRO)
macro_gal = ti.field(ti.i32, shape=N_MACRO)   # 0 or 1: which galaxy this mass belongs to

star_pos = ti.Vector.field(3, ti.f32, shape=N_STARS)
star_vel = ti.Vector.field(3, ti.f32, shape=N_STARS)
star_acc = ti.Vector.field(3, ti.f32, shape=N_STARS)
star_base_color = ti.Vector.field(3, ti.f32, shape=N_STARS)
star_brightness = ti.field(ti.f32, shape=N_STARS)
star_render_color = ti.Vector.field(3, ti.f32, shape=N_STARS)
star_twinkle_phase = ti.field(ti.f32, shape=N_STARS)
star_active = ti.field(ti.i32, shape=N_STARS)   # 0 = parked / invisible user-pool slot

# per-galaxy center of mass (position & velocity), recomputed every step
gal_com_pos = ti.Vector.field(3, ti.f32, shape=2)
gal_com_vel = ti.Vector.field(3, ti.f32, shape=2)
gal_com_mass = ti.field(ti.f32, shape=2)

sim_time = ti.field(ti.f32, shape=())
next_pool_slot = ti.field(ti.i32, shape=())   # cyclic write pointer for user-spawned stars

# Orbit trail history for the two galaxy cores (ring buffers)
TRAIL_LEN = 600
trail_pos = ti.Vector.field(3, ti.f32, shape=(2, TRAIL_LEN))
trail_head = ti.field(ti.i32, shape=2)
trail_count = ti.field(ti.i32, shape=2)

# Reference grid (static)
GRID_LINES = 41
GRID_EXTENT = 90.0
grid_verts = ti.Vector.field(3, ti.f32, shape=GRID_LINES * 4)

# Precomputed trail line-segment buffers (rebuilt each frame from trail_pos).
# Kept as two separate 1D fields (one per galaxy) because ti.ui.Scene.lines()
# expects a flat 1D vector field of consecutive (start,end) vertex pairs.
trail_segments = [ti.Vector.field(3, ti.f32, shape=2 * (TRAIL_LEN - 1)) for _ in range(2)]
trail_seg_color = [ti.Vector.field(3, ti.f32, shape=2 * (TRAIL_LEN - 1)) for _ in range(2)]

# Bright glow markers for the two galactic nuclei (rendered as large particles)
core_glow_pos = ti.Vector.field(3, ti.f32, shape=2)
core_glow_color = ti.Vector.field(3, ti.f32, shape=2)


# =========================================================================
# 4. GALAXY INITIALIZATION (host side, numpy) -> uploaded into fields
# =========================================================================
def enclosed_mass(core_mass, ring_masses, ring_radii, r):
    """Approximate mass enclosed within radius r, treating each ring as a
    thin shell (standard toy-model approximation: exact for a spherical
    shell, only approximate for an in-plane ring, but adequate for
    seeding a reasonable, flat-ish rotation curve). Vectorized over r,
    which may be a scalar or a numpy array."""
    r = np.asarray(r, dtype=np.float64)
    m = np.full_like(r, core_mass, dtype=np.float64)
    for mr, rr in zip(ring_masses, ring_radii):
        m = m + np.where(r >= rr, mr, 0.0)
    return m


def build_galaxy(seed, total_mass, disk_radius, thickness, center, bulk_vel, spin_dir, spiral_hand):
    """Builds the macro-particle skeleton + tracer stars for one galaxy.
    Returns dicts of numpy arrays ready to upload to Taichi fields.
    spin_dir = +1 or -1 (sense of disk rotation, about +z)
    spiral_hand = +1 or -1 (winding sense of the seeded spiral pattern)
    """
    rng = np.random.default_rng(seed)

    # ---- macro skeleton: core + concentric rings of point masses ----
    core_mass = total_mass * CORE_MASS_FRAC
    ring_masses_total = total_mass * RING_MASS_FRAC
    ring_radii = RING_RADIUS_FRAC * disk_radius

    macro_p = [np.array([0.0, 0.0, 0.0])]
    macro_v = [np.array([0.0, 0.0, 0.0])]
    macro_m = [core_mass]

    for ring_mass_total, rr in zip(ring_masses_total, ring_radii):
        m_each = ring_mass_total / MACROS_PER_RING
        v_circ = np.sqrt(G_SIM * enclosed_mass(core_mass, ring_masses_total, ring_radii, rr)
                          / (rr + SOFTENING))
        for k in range(MACROS_PER_RING):
            theta = 2.0 * np.pi * k / MACROS_PER_RING
            p = np.array([rr * np.cos(theta), rr * np.sin(theta), 0.0])
            tangential = np.array([-np.sin(theta), np.cos(theta), 0.0]) * spin_dir
            v = tangential * v_circ
            macro_p.append(p)
            macro_v.append(v)
            macro_m.append(m_each)

    macro_p = np.array(macro_p) + center
    macro_v = np.array(macro_v) + bulk_vel
    macro_m = np.array(macro_m)

    # ---- tracer stars ----
    n = N_STARS_PER_GALAXY
    n_bulge = int(n * BULGE_FRACTION)
    n_disk = n - n_bulge

    pos = np.zeros((n, 3))
    vel = np.zeros((n, 3))
    color = np.zeros((n, 3))
    bright = np.zeros(n)

    # -- disk population, seeded along a 2-arm logarithmic spiral --
    # exponential surface-density profile: more stars at small radius
    u = rng.random(n_disk)
    scale_len = disk_radius * 0.32
    r = -scale_len * np.log(1.0 - u * (1.0 - np.exp(-disk_radius / scale_len)))
    r = np.clip(r, 0.05, disk_radius)

    pitch = np.deg2rad(14.0)  # spiral pitch angle: tighter winding = smaller angle
    r0 = disk_radius * 0.12
    spiral_theta = spiral_hand * np.log(np.maximum(r, r0) / r0) / np.tan(pitch)

    arm_choice = rng.integers(0, 2, n_disk)              # which of the 2 arms
    on_arm = rng.random(n_disk) < 0.72                    # 72% clustered on arms, rest diffuse disk
    theta_random = rng.uniform(0, 2 * np.pi, n_disk)
    theta_arm = arm_choice * np.pi + spiral_theta + rng.normal(0, 0.28, n_disk)
    theta = np.where(on_arm, theta_arm, theta_random)

    z = rng.laplace(0.0, thickness * 0.5, n_disk)  # thin exponential-ish vertical profile

    x = r * np.cos(theta)
    y = r * np.sin(theta)

    v_circ = np.sqrt(G_SIM * enclosed_mass(core_mass, ring_masses_total, ring_radii, r)
                      / (r + SOFTENING))
    dispersion = 0.06  # velocity "temperature" of the disk, as a fraction of v_circ
    vx = -np.sin(theta) * v_circ * spin_dir + rng.normal(0, 1, n_disk) * v_circ * dispersion
    vy = np.cos(theta) * v_circ * spin_dir + rng.normal(0, 1, n_disk) * v_circ * dispersion
    vz = rng.normal(0, 1, n_disk) * v_circ * dispersion * 0.4

    pos[:n_disk] = np.stack([x, y, z], axis=1)
    vel[:n_disk] = np.stack([vx, vy, vz], axis=1)

    # color: cooler/younger (bluer) in the outer arms, warmer toward the core,
    # plus small per-star random hue jitter so the field doesn't look flat
    radial_frac = np.clip(r / disk_radius, 0.0, 1.0)
    bright[:n_disk] = np.clip(1.35 * np.exp(-r / (scale_len * 1.3)), 0.18, 1.5) * rng.uniform(0.6, 1.3, n_disk)

    # -- bulge population: puffy spheroid around the core --
    br = rng.exponential(disk_radius * 0.055, n_bulge)
    br = np.clip(br, 0.02, disk_radius * 0.28)
    bth = rng.uniform(0, 2 * np.pi, n_bulge)
    bph = np.arccos(rng.uniform(-1, 1, n_bulge))
    bx = br * np.sin(bph) * np.cos(bth)
    by = br * np.sin(bph) * np.sin(bth)
    bz = br * np.cos(bph) * 0.6

    v_circ_b = np.sqrt(G_SIM * enclosed_mass(core_mass, ring_masses_total, ring_radii, br)
                        / (br + SOFTENING))
    # bulge kinematics are hotter / more isotropic (pressure-supported, not cold-rotation-supported)
    bvx = -np.sin(bth) * v_circ_b * spin_dir * 0.5 + rng.normal(0, 1, n_bulge) * v_circ_b * 0.5
    bvy = np.cos(bth) * v_circ_b * spin_dir * 0.5 + rng.normal(0, 1, n_bulge) * v_circ_b * 0.5
    bvz = rng.normal(0, 1, n_bulge) * v_circ_b * 0.4

    pos[n_disk:] = np.stack([bx, by, bz], axis=1)
    vel[n_disk:] = np.stack([bvx, bvy, bvz], axis=1)
    bright[n_disk:] = np.clip(1.6 * np.exp(-br / (disk_radius * 0.08)), 0.5, 2.0) * rng.uniform(0.8, 1.2, n_bulge)

    pos += center
    vel += bulk_vel

    return {
        "macro_pos": macro_p, "macro_vel": macro_v, "macro_mass": macro_m,
        "star_pos": pos, "star_vel": vel, "bright": bright,
        "n_disk": n_disk, "radial_frac_disk": radial_frac,
    }


def make_colors(n, n_disk, radial_frac_disk, hue_rgb_inner, hue_rgb_outer, rng):
    """Blend an inner (bulge/old population) hue into an outer (young arm) hue."""
    color = np.zeros((n, 3))
    t_disk = radial_frac_disk[:, None]
    color[:n_disk] = hue_rgb_inner * (1 - t_disk) + hue_rgb_outer * t_disk
    color[n_disk:] = hue_rgb_inner * 1.05
    color += rng.uniform(-0.03, 0.03, color.shape)
    return np.clip(color, 0.0, 1.5)


def build_initial_conditions():
    """Sets up the full flyby -> tidal interaction -> merger encounter."""
    rng = np.random.default_rng(1234)

    sep = INITIAL_SEPARATION
    b = IMPACT_PARAMETER
    # place galaxies symmetric about the origin so the camera default framing works well
    half_sep = sep / 2.0
    center_a = np.array([-half_sep, -b / 2.0, 0.0])
    center_b = np.array([half_sep, b / 2.0, 0.0])

    # closing velocity along the line of approach, plus a small transverse
    # component from the impact parameter to give the encounter real orbital
    # angular momentum (this is what turns a head-on hit into a grazing,
    # tail-producing pass instead)
    approach_dir = (center_b - center_a)
    approach_dir = approach_dir / np.linalg.norm(approach_dir)
    transverse_dir = np.array([-approach_dir[1], approach_dir[0], 0.0])
    # v_rel = velocity of A relative to B: points mostly from A toward B (closing
    # the gap) plus a transverse component (from the impact parameter) that gives
    # the encounter real orbital angular momentum -- this is what turns a head-on
    # hit into a grazing, tail-producing pass instead.
    v_rel = approach_dir * INFALL_SPEED + transverse_dir * INFALL_SPEED * 0.22

    # split so total system momentum is ~zero (galaxies fall toward a common
    # barycenter rather than one being artificially held "stationary")
    mtot = MASS_A + MASS_B
    vel_a = v_rel * (MASS_B / mtot)
    vel_b = -v_rel * (MASS_A / mtot)

    gal_a = build_galaxy(1, MASS_A, DISK_RADIUS_A, DISK_THICKNESS_A, center_a, vel_a, spin_dir=1, spiral_hand=1)
    gal_b = build_galaxy(2, MASS_B, DISK_RADIUS_B, DISK_THICKNESS_B, center_b, vel_b, spin_dir=-1, spiral_hand=-1)

    milkyway_inner = np.array([1.15, 0.85, 0.55])   # warm bulge core
    milkyway_outer = np.array([0.55, 0.72, 1.05])   # cool blue-white arms
    andromeda_inner = np.array([1.2, 0.65, 0.45])   # warm amber core
    andromeda_outer = np.array([1.05, 0.75, 0.42])  # gold arms

    color_a = make_colors(N_STARS_PER_GALAXY, gal_a["n_disk"], gal_a["radial_frac_disk"],
                           milkyway_inner, milkyway_outer, rng)
    color_b = make_colors(N_STARS_PER_GALAXY, gal_b["n_disk"], gal_b["radial_frac_disk"],
                           andromeda_inner, andromeda_outer, rng)

    macro_p = np.concatenate([gal_a["macro_pos"], gal_b["macro_pos"]], axis=0)
    macro_v = np.concatenate([gal_a["macro_vel"], gal_b["macro_vel"]], axis=0)
    macro_m = np.concatenate([gal_a["macro_mass"], gal_b["macro_mass"]], axis=0)
    macro_g = np.concatenate([np.zeros(N_MACRO_PER_GALAXY), np.ones(N_MACRO_PER_GALAXY)]).astype(np.int32)

    star_p = np.zeros((N_STARS, 3), dtype=np.float32)
    star_v = np.zeros((N_STARS, 3), dtype=np.float32)
    star_c = np.zeros((N_STARS, 3), dtype=np.float32)
    star_b = np.zeros(N_STARS, dtype=np.float32)
    star_a = np.zeros(N_STARS, dtype=np.int32)

    a0, a1 = 0, N_STARS_PER_GALAXY
    b0, b1 = a1, a1 + N_STARS_PER_GALAXY
    star_p[a0:a1] = gal_a["star_pos"]
    star_v[a0:a1] = gal_a["star_vel"]
    star_c[a0:a1] = color_a
    star_b[a0:a1] = gal_a["bright"]
    star_a[a0:a1] = 1

    star_p[b0:b1] = gal_b["star_pos"]
    star_v[b0:b1] = gal_b["star_vel"]
    star_c[b0:b1] = color_b
    star_b[b0:b1] = gal_b["bright"]
    star_a[b0:b1] = 1

    # user-spawn pool: parked at the origin, invisible (brightness 0) until fired
    star_c[b1:] = np.array([1.0, 1.0, 1.0])

    return {
        "macro_p": macro_p.astype(np.float32), "macro_v": macro_v.astype(np.float32),
        "macro_m": macro_m.astype(np.float32), "macro_g": macro_g,
        "star_p": star_p, "star_v": star_v, "star_c": star_c, "star_b": star_b, "star_a": star_a,
    }


def upload_initial_conditions():
    ic = build_initial_conditions()
    macro_pos.from_numpy(ic["macro_p"])
    macro_vel.from_numpy(ic["macro_v"])
    macro_mass.from_numpy(ic["macro_m"])
    macro_gal.from_numpy(ic["macro_g"])

    star_pos.from_numpy(ic["star_p"])
    star_vel.from_numpy(ic["star_v"])
    star_base_color.from_numpy(ic["star_c"])
    star_brightness.from_numpy(ic["star_b"])
    star_active.from_numpy(ic["star_a"])

    twinkle = np.random.default_rng(7).uniform(0, 2 * np.pi, N_STARS).astype(np.float32)
    star_twinkle_phase.from_numpy(twinkle)

    sim_time[None] = 0.0
    next_pool_slot[None] = 0
    trail_head[0] = 0
    trail_head[1] = 0
    trail_count[0] = 0
    trail_count[1] = 0


def build_grid():
    verts = np.zeros((GRID_LINES * 4, 3), dtype=np.float32)
    coords = np.linspace(-GRID_EXTENT, GRID_EXTENT, GRID_LINES)
    idx = 0
    for c in coords:
        verts[idx] = [c, -GRID_EXTENT, 0.0]; idx += 1
        verts[idx] = [c, GRID_EXTENT, 0.0]; idx += 1
        verts[idx] = [-GRID_EXTENT, c, 0.0]; idx += 1
        verts[idx] = [GRID_EXTENT, c, 0.0]; idx += 1
    grid_verts.from_numpy(verts)


# =========================================================================
# 5. GRAVITATIONAL SOLVER (Taichi kernels)
# =========================================================================
@ti.func
def softened_accel(pos_from, pos_to, mass_to):
    """Newtonian acceleration on a body at pos_from due to a mass at pos_to,
    with Plummer-style softening: a = G*m*r_vec / (r^2 + eps^2)^1.5"""
    d = pos_to - pos_from
    r2 = d.dot(d) + SOFTENING2
    inv_r3 = 1.0 / (r2 * ti.sqrt(r2))
    return d * (G_SIM * mass_to * inv_r3)


@ti.kernel
def compute_galaxy_com():
    for g in range(2):
        gal_com_pos[g] = ti.Vector([0.0, 0.0, 0.0])
        gal_com_vel[g] = ti.Vector([0.0, 0.0, 0.0])
        gal_com_mass[g] = 0.0
    for i in range(N_MACRO):
        g = macro_gal[i]
        m = macro_mass[i]
        gal_com_pos[g] += macro_pos[i] * m
        gal_com_vel[g] += macro_vel[i] * m
        gal_com_mass[g] += m
    for g in range(2):
        gal_com_pos[g] /= gal_com_mass[g]
        gal_com_vel[g] /= gal_com_mass[g]


@ti.kernel
def compute_macro_accel():
    for i in range(N_MACRO):
        acc = ti.Vector([0.0, 0.0, 0.0])
        for j in range(N_MACRO):
            if j != i:
                acc += softened_accel(macro_pos[i], macro_pos[j], macro_mass[j])
        macro_acc[i] = acc

    # --- simplified Chandrasekhar dynamical friction between the two galaxies ---
    # Represents drag from each galaxy plowing through the other's extended
    # (unmodeled) dark-matter halo; strength falls off with separation via an
    # assumed isothermal-like halo density profile ~ 1/(r^2 + core^2), and
    # is applied as a uniform deceleration of each galaxy's bulk motion
    # relative to the other, with masses balanced so total momentum is conserved.
    sep_vec = gal_com_pos[1] - gal_com_pos[0]
    sep2 = sep_vec.dot(sep_vec) + SOFTENING2
    v_rel = gal_com_vel[1] - gal_com_vel[0]
    v_rel_mag = ti.sqrt(v_rel.dot(v_rel)) + VELOCITY_SOFTENING
    halo_falloff = 1.0 / (sep2 + DYN_FRICTION_CORE_RADIUS * DYN_FRICTION_CORE_RADIUS)
    drag_accel_mag = DYN_FRICTION_COEFF * halo_falloff
    drag_dir = v_rel / v_rel_mag
    # deceleration applied to galaxy 1 (relative motion), reaction on galaxy 0
    # scaled by mass ratio so net momentum change stays ~0
    accel_on_1 = -drag_dir * drag_accel_mag
    accel_on_0 = -accel_on_1 * (gal_com_mass[1] / gal_com_mass[0])
    for i in range(N_MACRO):
        if macro_gal[i] == 0:
            macro_acc[i] += accel_on_0
        else:
            macro_acc[i] += accel_on_1


@ti.kernel
def kick_macro(dt: ti.f32):
    for i in range(N_MACRO):
        macro_vel[i] += 0.5 * dt * macro_acc[i]


@ti.kernel
def drift_macro(dt: ti.f32):
    for i in range(N_MACRO):
        macro_pos[i] += dt * macro_vel[i]


@ti.kernel
def compute_star_accel():
    for s in range(N_STARS):
        acc = ti.Vector([0.0, 0.0, 0.0])
        p = star_pos[s]
        for j in range(N_MACRO):
            acc += softened_accel(p, macro_pos[j], macro_mass[j])
        star_acc[s] = acc


@ti.kernel
def kick_stars(dt: ti.f32):
    for s in range(N_STARS):
        star_vel[s] += 0.5 * dt * star_acc[s] * star_active[s]


@ti.kernel
def drift_stars(dt: ti.f32):
    for s in range(N_STARS):
        star_pos[s] += dt * star_vel[s] * star_active[s]


@ti.kernel
def recycle_escaped_stars():
    barycenter = (gal_com_pos[0] * gal_com_mass[0] + gal_com_pos[1] * gal_com_mass[1]) \
                 / (gal_com_mass[0] + gal_com_mass[1])
    for s in range(N_STARS):
        if star_active[s] == 1:
            d = star_pos[s] - barycenter
            if d.dot(d) > ESCAPE_RADIUS * ESCAPE_RADIUS:
                # respawn into whichever galaxy remnant is nearer, on a fresh
                # circular-ish orbit, so the disks stay visually full forever
                nearer = 0
                d0 = star_pos[s] - gal_com_pos[0]
                d1 = star_pos[s] - gal_com_pos[1]
                if d0.dot(d0) > d1.dot(d1):
                    nearer = 1
                rad = ti.sqrt(ti.random()) * 8.0 + 0.5
                theta = ti.random() * 6.2831853
                z = (ti.random() - 0.5) * 0.4
                local = ti.Vector([rad * ti.cos(theta), rad * ti.sin(theta), z])
                v_circ = ti.sqrt(G_SIM * gal_com_mass[nearer] / (rad + SOFTENING)) * 0.7
                tangential = ti.Vector([-ti.sin(theta), ti.cos(theta), 0.0])
                star_pos[s] = gal_com_pos[nearer] + local
                star_vel[s] = gal_com_vel[nearer] + tangential * v_circ


@ti.kernel
def update_render_colors(t: ti.f32):
    for s in range(N_STARS):
        twinkle = 1.0 + 0.06 * ti.sin(t * 2.3 + star_twinkle_phase[s])
        b = star_brightness[s] * twinkle * star_active[s]
        star_render_color[s] = star_base_color[s] * b


@ti.kernel
def push_trail(g: ti.i32, pos: ti.types.vector(3, ti.f32)):
    h = trail_head[g]
    trail_pos[g, h] = pos
    trail_head[g] = (h + 1) % TRAIL_LEN
    if trail_count[g] < TRAIL_LEN:
        trail_count[g] += 1


def _make_build_trail_segments(g):
    segs = trail_segments[g]
    cols = trail_seg_color[g]
    base_color = ti.Vector([0.9, 0.75, 0.35]) if g == 0 else ti.Vector([0.4, 0.75, 1.0])

    @ti.kernel
    def build():
        cnt = trail_count[g]
        for k in range(TRAIL_LEN - 1):
            if k < cnt - 1:
                i0 = (trail_head[g] - 1 - k) % TRAIL_LEN
                i1 = (trail_head[g] - 2 - k) % TRAIL_LEN
                if i0 < 0:
                    i0 += TRAIL_LEN
                if i1 < 0:
                    i1 += TRAIL_LEN
                segs[2 * k] = trail_pos[g, i0]
                segs[2 * k + 1] = trail_pos[g, i1]
                fade = 1.0 - k / ti.cast(TRAIL_LEN, ti.f32)
                cols[2 * k] = base_color * fade
                cols[2 * k + 1] = base_color * fade
            else:
                segs[2 * k] = trail_pos[g, trail_head[g]]
                segs[2 * k + 1] = trail_pos[g, trail_head[g]]
                cols[2 * k] = ti.Vector([0.0, 0.0, 0.0])
                cols[2 * k + 1] = ti.Vector([0.0, 0.0, 0.0])

    return build


build_trail_segments_0 = _make_build_trail_segments(0)
build_trail_segments_1 = _make_build_trail_segments(1)


@ti.kernel
def update_core_glow():
    core_glow_pos[0] = macro_pos[0]
    core_glow_pos[1] = macro_pos[N_MACRO_PER_GALAXY]
    # brighten the nucleus glow with how tightly the two cores have merged,
    # so the remnant's single nucleus reads as more luminous post-merger
    sep = macro_pos[0] - macro_pos[N_MACRO_PER_GALAXY]
    d = ti.sqrt(sep.dot(sep))
    boost = 1.0 + 1.5 / (1.0 + d * 0.15)
    core_glow_color[0] = ti.Vector([1.0, 0.85, 0.55]) * boost
    core_glow_color[1] = ti.Vector([1.0, 0.7, 0.45]) * boost


@ti.kernel
def spawn_probe_burst(cx: ti.f32, cy: ti.f32, cz: ti.f32, start_idx: ti.i32, count: ti.i32):
    for k in range(count):
        idx = (start_idx + k) % N_USER_POOL + 2 * N_STARS_PER_GALAXY
        r = ti.random() * 1.5
        theta = ti.random() * 6.2831853
        star_pos[idx] = ti.Vector([cx + r * ti.cos(theta), cy + r * ti.sin(theta), cz + (ti.random() - 0.5) * 0.5])
        speed = 0.05 + ti.random() * 0.08
        vth = ti.random() * 6.2831853
        star_vel[idx] = ti.Vector([speed * ti.cos(vth), speed * ti.sin(vth), (ti.random() - 0.5) * 0.03])
        star_brightness[idx] = 1.8
        star_active[idx] = 1


# =========================================================================
# 6. SIMULATION STEP (leapfrog / velocity-Verlet: kick-drift-kick)
# =========================================================================
def physics_step(dt):
    compute_galaxy_com()
    compute_macro_accel()
    kick_macro(dt)
    drift_macro(dt)

    compute_star_accel()
    kick_stars(dt)
    drift_stars(dt)

    # second half-kick using the field at the NEW positions (proper leapfrog)
    compute_galaxy_com()
    compute_macro_accel()
    kick_macro(dt)
    compute_star_accel()
    kick_stars(dt)

    recycle_escaped_stars()
    sim_time[None] += dt


# =========================================================================
# 7. CAMERA (manual orbit / pan / zoom, built from documented ti.ui inputs only)
# =========================================================================
class OrbitCamera:
    def __init__(self):
        self.target = np.array([0.0, 0.0, 0.0])
        self.azimuth = 0.9      # radians around +z
        self.elevation = 0.55   # radians above the xy plane
        self.distance = 130.0
        self.min_dist = 8.0
        self.max_dist = 500.0
        self._last_mouse = None

    def eye(self):
        ce = np.cos(self.elevation)
        return self.target + self.distance * np.array([
            ce * np.cos(self.azimuth), ce * np.sin(self.azimuth), np.sin(self.elevation)
        ])

    def basis(self):
        """Right & up vectors of the current view, for panning."""
        forward = self.target - self.eye()
        forward = forward / (np.linalg.norm(forward) + 1e-9)
        world_up = np.array([0.0, 0.0, 1.0])
        right = np.cross(forward, world_up)
        right = right / (np.linalg.norm(right) + 1e-9)
        up = np.cross(right, forward)
        return right, up

    def handle_input(self, window):
        mouse = np.array(window.get_cursor_pos())
        if self._last_mouse is None:
            self._last_mouse = mouse
        dx, dy = mouse - self._last_mouse

        if window.is_pressed(ti.ui.LMB):
            self.azimuth -= dx * 3.2
            self.elevation = float(np.clip(self.elevation + dy * 3.2, -1.45, 1.45))
        elif window.is_pressed(ti.ui.RMB):
            right, up = self.basis()
            pan_scale = self.distance * 0.9
            self.target -= right * dx * pan_scale
            self.target -= up * dy * pan_scale

        if window.is_pressed('w'):
            self.distance *= 0.985
        if window.is_pressed('s'):
            self.distance *= 1.015
        self.distance = float(np.clip(self.distance, self.min_dist, self.max_dist))

        self._last_mouse = mouse

    def zoom(self, factor):
        self.distance = float(np.clip(self.distance * factor, self.min_dist, self.max_dist))


# =========================================================================
# 8. MAIN LOOP: window, scene, UI, controls
# =========================================================================
def main():
    print(__doc__)

    build_grid()
    upload_initial_conditions()

    window = ti.ui.Window("Milky Way - Andromeda Collision Laboratory", (1280, 800), vsync=True)
    canvas = window.get_canvas()
    scene = window.get_scene()
    camera = ti.ui.Camera()
    orbit = OrbitCamera()

    paused = False
    time_scale = 1.0
    show_grid = True
    show_trails = True
    frame_count = 0
    trail_stride = 6   # only push a trail point every few frames (keeps history long in sim-time)

    print(f"Bodies: {N_MACRO} gravity-skeleton masses driving {N_STARS} tracer stars.")
    print("Window open. Controls are listed above; have fun flying around the collision.")

    while window.running:
        for e in window.get_events(ti.ui.PRESS):
            if e.key == ti.ui.ESCAPE:
                window.running = False
            elif e.key == ti.ui.SPACE:
                paused = not paused
            elif e.key == 'r':
                upload_initial_conditions()
                orbit.__init__()
                time_scale = 1.0
            elif e.key in (']', ti.ui.UP):
                time_scale = float(np.clip(time_scale * 1.4, MIN_TIME_SCALE, MAX_TIME_SCALE))
            elif e.key in ('[', ti.ui.DOWN):
                time_scale = float(np.clip(time_scale / 1.4, MIN_TIME_SCALE, MAX_TIME_SCALE))
            elif e.key == 'g':
                show_grid = not show_grid
            elif e.key == 't':
                show_trails = not show_trails
            elif e.key == ti.ui.LMB and window.is_pressed(ti.ui.SHIFT):
                mx, my = window.get_cursor_pos()
                ndc_x = (mx - 0.5) * 2.0
                ndc_y = (my - 0.5) * 2.0
                eye = orbit.eye()
                right, up = orbit.basis()
                forward = (orbit.target - eye)
                forward = forward / (np.linalg.norm(forward) + 1e-9)
                fov_scale = np.tan(np.deg2rad(45.0 / 2.0))
                aspect = 1280.0 / 800.0
                ray_dir = forward + right * (ndc_x * fov_scale * aspect) + up * (ndc_y * fov_scale)
                ray_dir = ray_dir / (np.linalg.norm(ray_dir) + 1e-9)
                if abs(ray_dir[2]) > 1e-6:
                    tpar = -eye[2] / ray_dir[2]
                    if tpar > 0:
                        hit = eye + ray_dir * tpar
                        start = int(next_pool_slot[None])
                        spawn_probe_burst(float(hit[0]), float(hit[1]), 0.0, start, 60)
                        next_pool_slot[None] = (start + 60) % N_USER_POOL

        orbit.handle_input(window)

        if not paused:
            steps = int(np.clip(round(STEPS_PER_FRAME_BASE * time_scale), 1, MAX_STEPS_PER_FRAME))
            for _ in range(steps):
                physics_step(DT_BASE)
            frame_count += 1
            if frame_count % trail_stride == 0:
                push_trail(0, gal_com_pos[0])
                push_trail(1, gal_com_pos[1])
            if os.environ.get("SIM_DEBUG") and frame_count % 30 == 0:
                com_np = gal_com_pos.to_numpy()
                sep = com_np[0] - com_np[1]
                print(f"[debug] t={sim_time[None]:7.2f}  separation={np.linalg.norm(sep):7.2f} kpc", flush=True)

        update_render_colors(sim_time[None])

        camera.position(*orbit.eye())
        camera.lookat(*orbit.target)
        camera.up(0.0, 0.0, 1.0)
        camera.fov(45.0)
        scene.set_camera(camera)
        scene.ambient_light((0.75, 0.75, 0.8))
        scene.point_light(pos=(60.0, 60.0, 90.0), color=(0.5, 0.5, 0.55))

        if show_grid:
            scene.lines(grid_verts, color=(0.12, 0.16, 0.22), width=1.0)

        if show_trails:
            build_trail_segments_0()
            build_trail_segments_1()
            scene.lines(trail_segments[0], per_vertex_color=trail_seg_color[0], width=2.0)
            scene.lines(trail_segments[1], per_vertex_color=trail_seg_color[1], width=2.0)

        scene.particles(star_pos, radius=0.09, per_vertex_color=star_render_color)

        # bright galactic-nucleus glow markers (the two dense cores)
        update_core_glow()
        scene.particles(core_glow_pos, radius=0.55, per_vertex_color=core_glow_color)

        canvas.set_background_color((0.01, 0.01, 0.02))
        canvas.scene(scene)

        gui = window.get_gui()
        with gui.sub_window("Simulation", 0.01, 0.01, 0.30, 0.16) as w:
            w.text(f"t = {sim_time[None]:.2f} units  (~{sim_time[None]*MYR_PER_TIME_UNIT:.0f} Myr)")
            w.text(f"time scale: {time_scale:.2f}x   {'PAUSED' if paused else 'running'}")
            w.text(f"stars: {N_STARS}   skeleton masses: {N_MACRO}")
            w.text("SPACE pause | R reset | ]/[ speed | Shift+Click spawn")

        window.show()


if __name__ == "__main__":
    main()
