"""
Generate docs/ASSUMPTIONS.md: every assumption and approximation, with the size of each
neglected physical effect COMPUTED from the actual system and compared with the timing noise.

The master rules forbid adding general relativity "without scientific justification" and
require every approximation to be documented. Both are satisfied by estimating each neglected
effect quantitatively: an effect is left out only if it is far below the smallest published
per-transit timing uncertainty.

Run: uv run --python 3.12 --extra dev python scripts/build_assumptions_doc.py
"""

from __future__ import annotations

import json
import math
from pathlib import Path

import numpy as np

from invisible_planet import constants as C

ROOT = Path(__file__).resolve().parents[1]
C_LIGHT = 299792458.0                      # m/s, exact
AU_LIGHT_S = C.AU_SI / C_LIGHT             # light-travel time across 1 au [s]


def main() -> None:
    ref = json.loads((ROOT / "data" / "kepler90_reference.json").read_text(encoding="utf-8"))
    pattern = json.loads((ROOT / "data" / "kepler90_observed_transits.json").read_text(encoding="utf-8"))
    m_star = ref["star"]["mass_solar"]["value"]
    r_star_au = C.solar_radii_to_au(ref["star"]["radius_solar"]["value"])
    planets = {}
    for k, p in ref["planets"].items():
        m = p["mass_earth"]["value"] * C.EARTH_MASS_IN_SOLAR
        planets[k] = {"m": m, "P": p["orbital_period_days"]["value"],
                      "a": C.kepler_third_law_axis(p["orbital_period_days"]["value"], m_star + m)}

    best_sigma_s = min(pattern["planets"][k]["median_sigma_seconds"] for k in pattern["probe_planets"])
    all_sigma = {k: pattern["planets"][k]["median_sigma_seconds"] for k in pattern["probe_planets"]}

    # ---- light-travel-time effects ------------------------------------------------------
    star_reflex_au = max(planets[k]["m"] * planets[k]["a"] / m_star for k in planets)
    ltte_reflex_s = star_reflex_au * AU_LIGHT_S
    ltte_constant_s = {k: planets[k]["a"] * AU_LIGHT_S for k in ("d", "e")}

    # ---- general relativity -------------------------------------------------------------
    gm = C.GM_SUN_SI * m_star
    gr_freq = {k: 3.0 * gm / (C_LIGHT**2 * planets[k]["a"] * C.AU_SI) for k in planets}   # fractional period shift
    baseline_days = 1459.5
    gr_timing_b_s = gr_freq["b"] * baseline_days * 86400.0
    ttv_b = 110.0                                           # measured O-C signal of b [s], docs/NUMERICAL_METHODS.md
    gr_ttv_part_s = gr_freq["b"] * ttv_b

    # ---- stellar oblateness ---------------------------------------------------------------
    j2_upper = 1e-6
    j2_period_b = 1.5 * j2_upper * (r_star_au / planets["b"]["a"]) ** 2

    # ---- symmetric-transit assumption for slightly eccentric visible orbits -------------------
    # Order-of-magnitude asymmetry: the planet's speed changes across the transit by a fraction
    # ~ e * (angular span of the transit) = e * 2 pi (T/P), displacing the mid-time by about
    # (T/2) times that fraction. e is the largest osculating eccentricity measured in the baseline
    # integration (data/baseline_stability.json); T is the KOI-table duration.
    koi = {}
    import pandas as pd
    table = pd.read_csv(ROOT / "data" / "raw" / "kepler90_koi_cumulative.csv")
    for _, row in table.iterrows():
        koi[row["kepler_name"].split()[-1]] = float(row["koi_duration"]) / 24.0
    baseline_path = ROOT / "data" / "baseline_stability.json"
    e_max = {k: 0.003 for k in ("d", "e")}
    if baseline_path.exists():
        b = json.loads(baseline_path.read_text(encoding="utf-8"))
        e_max = {k: b["planets"][k]["e_max"] for k in ("d", "e")}
    asym_s = {k: 0.5 * koi[k] * e_max[k] * 2.0 * math.pi * koi[k] / planets[k]["P"] * 86400.0 for k in ("d", "e")}

    lines = [
        "# Assumptions, approximations and neglected effects",
        "",
        "**Generated by `scripts/build_assumptions_doc.py`. Every magnitude below is computed from the",
        "system's parameters, not typed by hand.**",
        "",
        "> Planet X is synthetic. Nothing here is a claim about the real Kepler-90 system having a",
        "> ninth planet.",
        "",
        "## 1. What the model includes",
        "",
        "* Newtonian gravity between the star, the eight planets and (in the experiment) one",
        "  additional body, as point masses, integrated with velocity Verlet (fixed step) in f64.",
        "* Initial conditions: the star and planets' published masses and periods, with each planet's",
        "  initial osculating period and mean anomaly fitted to the real transit times",
        "  (`invisible_planet/calibration/matching.py`).",
        "",
        "## 2. Modelling assumptions (choices, not facts)",
        "",
        "| Assumption | Status | Consequence |",
        "|---|---|---|",
        "| All eight visible planets on circular orbits | `adopted-model` | measured e exist only for g and h; the large real TTVs of g (≈1 day) are therefore only partly reproduced |",
        "| Ascending node = 0 for every visible planet | `adopted-model` | unconstrained by transit photometry |",
        "| Inclinations from the published impact parameters | `derived` | h's published inclination implies it would not transit; see `docs/KEPLER90_DATA.md` |",
        "| Masses of b, c, i, d, e, f from a mass–radius relation | `derived` | **no published mass exists**; large scatter; b, c, i carry an ASSUMED 50% uncertainty |",
        "| Masses of g, h are the TTV masses | `observed` | other published values disagree (`KEPLER90_DATA.md`, CHECK 6) |",
        "| The visible-planet model is treated as KNOWN by the inference | modelling | the real orbital elements of d and e are uncertain; the linear ephemeris of each probe is profiled out, which absorbs a constant period/phase error but not an error in the visible planets' dynamics |",
        "| Timing noise independent Gaussian, published per-transit σ | modelling | real errors share systematics |",
        "| Only d and e are timing probes | data-driven rule | g has large real TTVs a circular model cannot reproduce; h has 3 transits |",
        "| Hidden planet on a nearly coplanar orbit (mutual inclination ≤ 6°) | prior | Kepler multi-planet systems are flat; a polar orbit is not considered |",
        "| Hidden planet does not transit | data-supported prior | no extra transit signal was seen; a 4 R⊕ transit would be ≈1e-3 deep against 2e-4 noise per cadence |",
        "",
        "## 3. Neglected physical effects, quantified",
        "",
        f"The smallest published per-transit timing uncertainty among the probes is **{best_sigma_s:.0f} s**",
        f"(all probes: {', '.join(f'{k}: {v:.0f} s' for k, v in all_sigma.items())}).",
        "",
        "| Effect | Size | Compared with the timing noise | Verdict |",
        "|---|---|---|---|",
        f"| Light-travel-time delay across the orbit, constant part | {ltte_constant_s['d']:.0f} s (d), {ltte_constant_s['e']:.0f} s (e) | not a signal: it is the same at every transit, absorbed by the fitted T₀ | left out |",
        f"| Variable light-travel time from the star's reflex motion (dominated by the most massive planet) | {ltte_reflex_s:.2f} s | {ltte_reflex_s / best_sigma_s:.1e} of σ | left out |",
        f"| General relativity: fractional period shift 3GM/(c²a), planet b | {gr_freq['b']:.1e} | over {baseline_days:.0f} d a phase drift of {gr_timing_b_s:.2f} s that is LINEAR in time, so absorbed by the fitted period; its effect on the TTV signal itself is {gr_ttv_part_s:.1e} s | left out |",
        f"| General relativity, planet d | {gr_freq['d']:.1e} | far smaller still | left out |",
        f"| Stellar oblateness (assumed J₂ ≤ {j2_upper:.0e}), fractional period shift of b | {j2_period_b:.1e} | absorbed by the fitted period | left out |",
        "| Tides and planetary oblateness | ≪ the above | — | left out |",
        "",
        "General relativity and light-travel time are therefore omitted on quantitative grounds, in line",
        "with the project rule that GR is not added without justification.",
        "",
        "## 4. What the transit time means",
        "",
        "The simulated transit centre is the instant of minimum sky-projected star–planet separation while",
        "the planet is in front of the star. Published mid-transit times come from fits of a symmetric",
        "light-curve model, which coincide with that instant for a circular orbit. For a slightly eccentric",
        "orbit the planet's speed changes across the transit, displacing the two by roughly",
        "(T/2)·e·2π(T/P) (an order-of-magnitude estimate). With the largest osculating eccentricities seen",
        f"in the baseline integration (d: {e_max['d']:.1e}, e: {e_max['e']:.1e}) this is",
        f"{asym_s['d']:.1f} s for d and {asym_s['e']:.1f} s for e, against σ of {all_sigma['d']:.0f} s and {all_sigma['e']:.0f} s.",
        "",
        "## 5. Known limitations of the experiment",
        "",
        "* The hidden planet is **synthetic**. Its signal would be **inconsistent with the real published",
        "  transit times of d and e**, which show no significant TTV; it is a hypothetical scenario used to",
        "  test a method, not a candidate consistent with all Kepler data.",
        "* Only two probe planets exist, with per-transit uncertainties of 5–23 minutes; the experiment",
        "  is far more constrained than one with many precisely timed planets.",
        "* Kepler's observing gaps are reproduced only for the epochs actually listed in the published",
        "  tables.",
        "* Stellar activity and spot crossings are not modelled beyond what is in the published σ.",
        "",
    ]
    (ROOT / "docs" / "ASSUMPTIONS.md").write_text("\n".join(lines), encoding="utf-8")
    print("wrote docs/ASSUMPTIONS.md")
    print(f"  star reflex light-time {ltte_reflex_s:.3f} s; GR fractional shift (b) {gr_freq['b']:.2e}; "
          f"best sigma {best_sigma_s:.0f} s")


if __name__ == "__main__":
    main()
